apiVersion: v1
kind: Service
metadata:
  name: metastore
spec:
  ports:
    - port: 9083
  selector:
    app: metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
spec:
  selector:
    matchLabels:
      app: metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
        - name: metastore
          image: joshuarobinson/hivemetastore
          env:
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: metastore-cfg-vol
              mountPath: /opt/hive-metastore/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: metastore-cfg-vol
              mountPath: /opt/hive-metastore/conf/core-site.xml
              subPath: core-site.xml
          command: ["/opt/hive-metastore/bin/start-metastore"]
          args: ["-p", "9083"]
          resources:
            requests:
              memory: "1G"
              cpu: 1
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 9083
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: metastore-cfg-vol
          configMap:
            name: metastore-cfg
