apiVersion: v1
kind: Service
metadata:
  name: sqllineage-deployment-service
  labels:
    app: sqllineage
spec:
  type: LoadBalancer
  ports:
    - port: 5000
  selector:
    app: sqllineage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqllineage-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sqllineage
    spec:
      containers:
        - name: sqllineage
          image: reata/sqllineage:latest
          env:
            - name: PORT
              value: "5000"
  selector:
    matchLabels:
      app: sqllineage
